version: '3.9'

# Network for Laravel
networks:
  inewgent_network:
    name: inewgent
    driver: bridge

services:

  app:
    build: .
    # dockerfile: Dockerfile.dev
    image: crud-redux-app
    container_name: crud_redux_app
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      # - "3000:3000"
      - "3000:3000"
    restart: always
    networks:
      - inewgent_network
      
